spring:
    hadoop:
        fsUri: hdfs://sandbox.hortonworks.com:8020
        resourceManagerHost: sandbox.hortonworks.com
    yarn:
        appName: hw5-yarn
        applicationDir: /app/hw5-yarn/
        client:
            files:
              - "file:hw5-yarn-dist/target/hw5-yarn-dist/hw5-yarn-container-0.1.0.jar"
              - "file:hw5-yarn-dist/target/hw5-yarn-dist/hw5-yarn-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: hw5-yarn-appmaster-0.1.0.jar
        appmaster:
            containerCount: 1
            launchcontext:
                archiveFile: hw5-yarn-container-0.1.0.jar
