install: true
language: java

sudo: true

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8

branches:
  only:
  - master

script:
  - gradle check -q
  - gradle build
  - gradle assemble

git:
  depth: 10