spring:
  profiles: dev
  h2.console.settings.trace: false
  datasource:
    username: h2
    password:
    initialize: true
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: colmen
    generate-ddl: true
    hibernate:
      ddl-auto: drop-create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

logging:
  path: logs
  level:
    root: WARN
    org:
      springframework: INFO
      org.hibernate: WARN