spring:
  datasource:
    username: realtor
    password:
    url: jdbc:mysql://localhost/realtor-db
    initialize: false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: false
    database: mysql
    database-platform: MYSQL
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

logging:
  path: logs
  level:
    root: WARN
    org:
      springframework: WARN
      org.hibernate: WARN