server:
    port: ${port:8010}
spring:
    profiles:
        active: dev
    application:
        name: colmen
    datasource:
        username: h2
        password:
        driver-class-name: org.h2.Driver
    jpa:
        show-sql: true
        database-platform: org.hibernate.dialect.H2Dialect
        generate-ddl: true
        hibernate:
            ddl-auto: create-drop
logging:
    path: logs
    level:
        root: WARN
        org:
            springframework: INFO
            org.hibernate: WARN