CREATE TABLE IF NOT EXISTS Persons (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  Keywords (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE,
    PersonID INT NOT NULL,
    FOREIGN KEY (PersonID)
        REFERENCES Persons (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  Sites (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  Pages (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Url NVARCHAR(256) NOT NULL UNIQUE,
    SiteID INT NOT NULL,
    FoundDateTime DATE,
    LastScanDate DATE,
    FOREIGN KEY (SiteID)
        REFERENCES Sites (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  PersonPageRank (
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PersonID INT NOT NULL,
    PageID INT NOT NULL,
    Rank INT NOT NULL,
    FOREIGN KEY (PersonID)
        REFERENCES Persons (ID) ON DELETE CASCADE,
    FOREIGN KEY (PageID)
        REFERENCES Pages (ID) ON DELETE CASCADE
);