--USE colmen;

CREATE TABLE IF NOT EXISTS Persons (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  Keywords (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE,
    PersonID BIGINT NOT NULL,
    FOREIGN KEY (PersonID)
        REFERENCES Persons (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  Sites (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Name NVARCHAR(256) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS  Pages (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    Url NVARCHAR(256) NOT NULL UNIQUE,
    SiteID BIGINT NOT NULL,
    FoundDateTime DATE,
    LastScanDate DATE,
    FOREIGN KEY (SiteID)
        REFERENCES Sites (ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS  PersonPageRank (
    ID BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    PersonID BIGINT NOT NULL,
    PageID BIGINT NOT NULL,
    Rank INT NOT NULL,
    FOREIGN KEY (PersonID)
        REFERENCES Persons (ID) ON DELETE CASCADE,
    FOREIGN KEY (PageID)
        REFERENCES Pages (ID) ON DELETE CASCADE
);