spring:
#    main.web-environment: false
    hadoop:
        fsUri: hdfs://sandbox.hortonworks.com:8020
        resourceManagerHost: sandbox.hortonworks.com
        resourceManagerPort: 8050
    yarn:
        appName: hw5-yarn
        applicationDir: /app/hw5-yarn/
        client:
            files:
              - "file:hw5-yarn-dist/target/hw5-yarn-dist/hw5-yarn-container-0.1.0.jar"
              - "file:hw5-yarn-dist/target/hw5-yarn-dist/hw5-yarn-appmaster-0.1.0.jar"
            launchcontext:
                archiveFile: hw5-yarn-appmaster-0.1.0.jar
        appmaster:
            appmasterClass: com.epam.yarn.appmaster.Appmaster
            keepContextAlive: true
            containerCount: 1
            launchcontext:
                archiveFile: hw5-yarn-container-0.1.0.jar
app:
    server:
        port: 9080
    urlResources: http://${spring.hadoop.resourceManagerHost}:8088/jmx?qry=Hadoop:service=ResourceManager,name=QueueMetrics,q0=root
    indexPath: templates/index.html
    input: /home/hw5/data
    output: /home/hw5/out